version: '2'
services:
  bootnode:
    image: ethereum/client-go:release-1.9
    command: --datadir /qdata/bootnode --port 30301 --rpc --rpcaddr "0.0.0.0" --rpcport 8545 --rpcapi "admin,net,eth" --nousb  -nodekey /qdata/bootnode/boot.key --networkid 2019 --netrestrict 172.13.0.0/24 --nat extip:172.13.0.100
    volumes:
      - '.:/qdata'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.100'

  node1:
    image: ethereum/client-go:release-1.9
    command: --datadir /qdata/node1 --syncmode 'full' --port 30311 --rpccorsdomain "*" --miner.gastarget 804247552 --rpc --rpcaddr "0.0.0.0" --rpcport 8545 --rpcapi 'admin,personal,db,eth,net,web3,txpool,miner,clique' --bootnodes enode://8223d73d6af37d770e8298252431ea6495d5b222a6052bcfc08a6f2f3e8c3570d9882a3e81fec406206c9d3d277d59a253a16c99b18227e92fd1302e728ff3d3@172.13.0.100:30301 --networkid 2019 --miner.gasprice 0 --unlock '0x0453b3761d9fca9439adef8ce17d51cf278baf00' --password /qdata/node1/password.txt --mine --nousb --allow-insecure-unlock --netrestrict 172.13.0.0/24
    ports:
      - 22001:8545
      - 22002:8546
    volumes:
      - '.:/qdata'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.2'

  node2:
    image: ethereum/client-go:release-1.9
    command: --datadir /qdata/node2 --syncmode 'full' --port 30311 --rpccorsdomain "*" --targetgaslimit 804247552 --rpc --rpcaddr "0.0.0.0" --rpcport 8545 --rpcapi 'admin,personal,db,eth,net,web3,txpool,miner,clique' --bootnodes enode://8223d73d6af37d770e8298252431ea6495d5b222a6052bcfc08a6f2f3e8c3570d9882a3e81fec406206c9d3d277d59a253a16c99b18227e92fd1302e728ff3d3@172.13.0.100:30301 --networkid 2019 --miner.gasprice 0 --unlock '0x37a809060f2cd38aefee06369b4eb543a3cba6c0' --password /qdata/node2/password.txt --mine --nousb --allow-insecure-unlock --netrestrict 172.13.0.0/24
    ports:
      - 23001:8545
      - 23002:8546
    volumes:
      - '.:/qdata'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.3'

networks:
  quorum_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/16
