version: '2'
services:
  init_node1:
    image: ethereum/client-go:release-1.8
    command: --datadir /qdata/node2 init /qdata/genesis.json
    volumes:
      - '.:/qdata'

  init_node2:
    image: ethereum/client-go:release-1.8
    command: --datadir /qdata/node2 init /qdata/genesis.json
    volumes:
      - '.:/qdata'

